"""
shared/auth.py — Team token authentication for hosted deployments.

Tokens are issued at registration (one per team; every bot of the team uses
it) and verified by the exchange at handshake when AUTH_REQUIRED=true.
Only sha256 hashes are stored server-side; the plaintext token is shown to
the student exactly once, in the registration response. A lost token is
regenerated by the teacher:

    python -m shared.auth regen <team_name>
    python -m shared.auth teacher       # (re)issue the teacher token

The teacher token authenticates role=teacher handshakes (session control,
shocks) and the dashboards.

Storage: TOKENS_PATH (default teacher/tokens.json, gitignored):
    { "<team_name>": "<sha256>", "__teacher__": "<sha256>" }
"""

from __future__ import annotations

import hashlib
import json
import os
import secrets
import sys

import shared.roster as roster_shape

TOKENS_PATH = os.environ.get(
    "TOKENS_PATH",
    os.path.join(os.path.dirname(__file__), "..", "teacher", "tokens.json"),
)

_TEACHER_KEY = "__teacher__"


def _load() -> dict[str, str]:
    try:
        with open(TOKENS_PATH) as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _save(store: dict[str, str]) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(TOKENS_PATH)), exist_ok=True)
    with open(TOKENS_PATH, "w") as f:
        json.dump(store, f, indent=2)
        f.write("\n")
    try:
        os.chmod(TOKENS_PATH, 0o600)
    except OSError:
        pass


def hash_token(token: str) -> str:
    return hashlib.sha256(token.encode()).hexdigest()


def issue_token(owner: str) -> str:
    """Create (or replace) the token for a team. Returns the plaintext once."""
    token = secrets.token_urlsafe(24)
    store = _load()
    store[owner] = hash_token(token)
    _save(store)
    return token


def issue_teacher_token() -> str:
    return issue_token(_TEACHER_KEY)


def verify(owner: str, token: str) -> bool:
    """True if `token` is the current token for `owner`."""
    if not token:
        return False
    stored = _load().get(owner)
    return stored is not None and secrets.compare_digest(stored, hash_token(token))


def verify_teacher(token: str) -> bool:
    return verify(_TEACHER_KEY, token)


def teacher_token_exists() -> bool:
    """True once a teacher token has been issued on this deployment.

    This is the "is this a hosted setup?" switch. Plain local play never runs
    `python -m shared.auth teacher`, so there is nothing to authenticate
    against and the dashboard keeps working exactly as it always has: anyone
    who can reach the port is the teacher. The moment a teacher token exists,
    session control is gated on it (see teacher/web_dashboard._command_allowed).
    """
    return bool(_load().get(_TEACHER_KEY))


def verify_any(token: str) -> bool:
    """True if `token` matches ANY registered team or the teacher.
    Used for observer connections (market-data access for members)."""
    if not token:
        return False
    h = hash_token(token)
    return any(secrets.compare_digest(stored, h) for stored in _load().values())


def team_for_bot(bot_id: str, roster_path: str) -> str | None:
    """Map a bot id (e.g. rocket_trader_1) to its team name via the roster."""
    try:
        with open(roster_path) as f:
            roster = json.load(f)
    except (OSError, ValueError):
        return None
    for team_name, cfg in roster.items():
        if bot_id in roster_shape.bot_ids_of(cfg):
            return team_name
    return None


def _main() -> None:
    if len(sys.argv) >= 2 and sys.argv[1] == "teacher":
        print(f"Teacher token (save it — shown once):\n  {issue_teacher_token()}")
    elif len(sys.argv) >= 3 and sys.argv[1] == "regen":
        owner = sys.argv[2]
        print(f"New token for {owner} (shown once):\n  {issue_token(owner)}")
    else:
        print("Usage:\n  python -m shared.auth teacher\n  python -m shared.auth regen <team_name>")


if __name__ == "__main__":
    _main()
